# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iOS_Template' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iOS_Template
  pod 'Alamofire'
  pod 'ObjectMapper'
  pod 'AlamofireObjectMapper'
  pod 'Bond'
  pod 'RealmSwift'
  pod 'Swinject'
  
  abstract_target 'Tests' do
    target 'iOS_Tests'
    target 'iOS_UITests'
    
    pod 'Quick'
    pod 'Nimble'
    pod 'Mockingjay'
    
  end
end

# Disable Code Coverage for Pods projects
post_install do |installer_representation|
  installer_representation.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['CLANG_ENABLE_CODE_COVERAGE'] = 'NO'
    end
  end
end
